ACTRESS_TOP_GROUND_MODE = 1 << 1

ACTRESS_TARGET_MODE = 1 << 2

ACTRESS_IMAGE_MODE = 1 << 3

ACTRESS_UPDATE_MODE = 1

ACTRESS_AGGR_MODE = ACTRESS_TOP_GROUND_MODE | ACTRESS_TARGET_MODE

MODE_MAP = {
    "image" : ACTRESS_IMAGE_MODE,
    "ground" : ACTRESS_TOP_GROUND_MODE,
    "target" : ACTRESS_TARGET_MODE,
    "update" : ACTRESS_UPDATE_MODE,
    "aggr" : ACTRESS_AGGR_MODE
}