MOVIE_COVER_IMG_DIR_FORMATTER = '{}/{}'

MOVIE_PREVIEW_IMG_DIR_FORMATTER = '{}/{}/preview'

ACTRESS_GALLERY_IMG_DIR_FORMATTER = '{}/{}/gallery'

ACTRESS_PROFILE_IMG_DIR_FORMATTER = '{}/{}'

IMG_DES_FORMATTER = '{}/{}.jpg'
