FALENO_ACTRESS_TOP = 'https://faleno.jp/top/actress/'

FALENO_ACTRESS_TARGET_FORMATTER = 'https://faleno.jp/top/actress/{}/'

FALENO_ACTRESS_EN_NAME_REGEX = r'(?<=actress\/)\w+'

FALENO_ACTRESS_DETAIL_BIRTH_TEXT = '誕生日'

FALENO_ACTRESS_DETAIL_HEIGHT_TEXT = '身長'

FALENO_ACTRESS_DETAIL_PLACE_TEXT = '出身地'

FALENO_ACTRESS_DETAIL_SIZE_TEXT = 'スリーサイズ'

FALENO_ACTRESS_DETAIL_HOBBY_TEXT = '趣味'

FALENO_ACTRESS_DETAIL_TRICK_TEXT = '特技'

FALENO_ACTRESS_NAME_ID_META_KEY = 'name_id'

FALENO_ACTRESS_PROFILE_IMGNAME = 'profile'

FALENO_ACTRESS_PROFILE_IMG_SUBDIR_FORMATTER = 'faleno/{}'