from re import compile

IDEAPOCKET_ACTRESS_ID_REGEX = r'(?<=\/)\d+'

IDEAPOCKET_ACTRESS_CLEAN_REGEX = compile(r'\s*\n\s*')

IDEAPOCKET_ACTRESS_BASE_URL = 'https://www.ideapocket.com'

IDEAPOCKET_ACTRESS_TOP = 'https://www.ideapocket.com/actress/'

IDEAPOCKET_ACTRESS_TARGET_FORMATTER = 'https://www.ideapocket.com/actress/detail/{}/'

IDEAPOCKET_ACTRESS_PROFILE_IMGNAME = 'profile'

IDEAPOCKET_ACTRESS_PROFILE_IMG_SUBDIR_FORMATTER = "ideapocket/{}"

IDEAPOCKET_ACTRESS_DETAIL_BIRTH_TEXT = '生年月日'

IDEAPOCKET_ACTRESS_DETAIL_HEIGHT_TEXT = '身長'

IDEAPOCKET_ACTRESS_DETAIL_SIZE_TEXT = 'スリーサイズ'

IDEAPOCKET_ACTRESS_DETAIL_PLACE_TEXT = '出身地'

IDEAPOCKET_ACTRESS_DETAIL_BLOOD_TEXT = '血液型'

IDEAPOCKET_ACTRESS_DETAIL_HOBBYTRICK_TEXT = '趣味/特技'

IDEAPOCKET_ACTRESS_DETAIL_TWITTER_TEXT = 'twitter'

IDEAPOCKET_ACTRESS_DETAIL_INS_TEXT = 'instagram'
