KAWAII_ACTRESS_PROFILE_IMG_SUBDIR_FORMATTER = 'kawii/{}'

KAWAII_BASE_URL = 'https://www.kawaiikawaii.jp'

KAWAII_ACTRESS_TOP = 'https://www.kawaiikawaii.jp/actress/'

KAWAII_ACTRESS_TARGET_FORMATTER = 'https://www.kawaiikawaii.jp/actress/detail/{}/'

KAWAII_ACTRESS_ID_REGEX = r'(?<=\/)\d+'

KAWAII_ACTRESS_PROFILE_IMGNAME = 'profile'

KAWAII_ACTRESS_DETAIL_BIRTH_TEXT = '生年月日'

KAWAII_ACTRESS_DETAIL_HEIGHT_TEXT = '身長'

KAWAII_ACTRESS_DETAIL_SIZE_TEXT = 'スリーサイズ'

KAWAII_ACTRESS_DETAIL_TRICK_TEXT = '特技'

KAWAII_ACTRESS_DETAIL_HOBBY_TEXT = '趣味'

KAWAII_ACTRESS_DETAIL_TWITTER_TEXT = 'twitter'

KAWAII_ACTRESS_DETAIL_INS_TEXT = 'instagram'