PRESTIGE_ACTRESS_TOP = 'https://www.prestige-av.com/actress/actress_top.php'

PRESTIGE_ACTRESS_TARGET_FORMATTER = 'https://www.prestige-av.com/actress/actress_detail.php?actress_id={}'

PRESTIGE_BASE_URL = 'https://www.prestige-av.com'

PRESTIGE_ACTRESS_PROFILE_IMG_SUBDIR_FORMATTER = 'prestige/{}'

PRESTIGE_ACTRESS_ID_REGEX = r'(?<=actress_id=)\d+$'

PRESTIGE_ACTRESSID_META_KEY = 'id'

PRESTIGE_ACTRESS_DETAIL_PLACE_TEXT = '出身地'

PRESTIGE_ACTRESS_DETAIL_BIRTH_TEXT = '生年月日'

PRESTIGE_ACTRESS_DETAIL_BLOOD_TYPE_TEXT = '血液型'

PRESTIGE_ACTRESS_DETAIL_HEIGHT_TEXT = '身長'

PRESTIGE_ACTRESS_DETAIL_SIZE_TEXT = 'スリーサイズ'

PRESTIGE_ACTRESS_DETAIL_HOBBY_TRICK_TEXT = '趣味/特技'

PRESTIGE_ACTRESS_DETAIL_TWITTER_TEXT = 'Twitter'

PRESTIGE_ACTRESS_DETAIL_INS_TEXT = 'Instagram'

PRESTIGE_ACTRESS_DETAIL_BOOKS_TEXT = '電子書籍'

S1_ACTRESS_PROFILE_IMGNAME = 'profile'
